name: Publish to WinGet

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description:
        required: true
        default: 'v1.0.2'

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - name: Run WinGet Releaser
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: MesterPerfect.IlmQuiz
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: 'IlmQuiz_Setup_.*\.exe'
          release-tag: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
